apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
$patch: delete
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
$patch: delete
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendationservice
$patch: delete

